import type { Creator, PaymentLink } from './types';

export const mockCreator: Creator = {
  creator_id: 'creator_1',
  display_name: 'Amadou',
  country: 'ML',
  default_currency: 'XOF',
  created_at: new Date().toISOString(),
};

export const mockPaymentLinks: PaymentLink[] = [
  {
    link_id: 'link_1',
    creator_id: 'creator_1',
    title: 'T-shirt "Mali Dev"',
    description: 'High-quality cotton t-shirt for developers in Mali.',
    amount_xof: 15000,
    slug: 't-shirt-mali-dev',
    status: 'ACTIVE',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    disabled_at: null,
  },
  {
    link_id: 'link_2',
    creator_id: 'creator_1',
    title: 'Consulting Session (1hr)',
    description: 'A one-hour consulting session on web development.',
    amount_xof: 75000,
    slug: 'consulting-1hr',
    status: 'PAID',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    disabled_at: null,
  },
  {
    link_id: 'link_3',
    creator_id: 'creator_1',
    title: 'Ebook: Mastering Next.js',
    description: 'A comprehensive guide to building modern web apps with Next.js.',
    amount_xof: 25000,
    slug: 'ebook-mastering-nextjs',
    status: 'ACTIVE',
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    disabled_at: null,
  },
    {
    link_id: 'link_4',
    creator_id: 'creator_1',
    title: 'Workshop Ticket: Intro to React',
    description: 'Ticket for a 2-day hands-on React workshop.',
    amount_xof: 50000,
    slug: 'workshop-react-intro',
    status: 'DISABLED',
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    disabled_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
    {
    link_id: 'link_5',
    creator_id: 'creator_1',
    title: 'Logo Design Package',
    description: 'Basic logo design package including 3 concepts and revisions.',
    amount_xof: 150000,
    slug: 'logo-design-basic',
    status: 'PAID',
    created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    disabled_at: null,
  },
];
